# hostname (and path) to the root eg. http://spf13.com/
baseurl = "https://appernetic.github.io"

# Site title
title = "Appernetic.io"

# Copyright
copyright = "(c) 2016 Appernetic.io"

# Language
languageCode = "en-EN"

# SES friendly url:s
canonifyurls = true

# Frontmatter format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "appernetic"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "GÃ¶ran Svensson"
    email = "support@appernetic.io"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Appernetic"
    topline = "A Static Site Generator as a Service"
    footline = "Coded with <i class='fa fa-heart'></i>. Theme: <a href='https://github.com/mmrath/hugo-bootstrap'>Hugo-bootstrap</a>"
    theme = "paper"
    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "https://appernetic.io"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "UA-73770938-2"

    # Sidebar social links.
    github = "https://github.com/appernetic/" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "https://www.facebook.com/appernetic/" # Your Facebook profile ID
    twitter = "https://twitter.com/appernetic" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
